from pathlib import Path
import re

import yaml


FIXTURE_DIR = Path(__file__).with_name("verified")


def cpp_ident(name: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if ident and ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def format_ticks(ticks: list[int]) -> str:
    lines = []
    for offset in range(0, len(ticks), 12):
        chunk = ticks[offset : offset + 12]
        suffix = "," if offset + 12 < len(ticks) else ""
        lines.append("    " + ", ".join(str(tick) for tick in chunk) + suffix)
    return "\n".join(lines)


def main() -> None:
    print("// Generated by tests/pc/fixtures/export_cpp_fixtures.py. Do not edit by hand.")
    print("#pragma once")
    print("")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print("")
    print("namespace test_fixtures")
    print("{")

    for path in sorted(FIXTURE_DIR.glob("*.yaml")):
        with path.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)

        name = cpp_ident(data["name"])
        bits = int(data["bits"])
        bit_length = int(data["bit_length"])
        ticks = data["raw_ticks"]

        print(f"inline constexpr uint64_t {name}_bits = 0x{bits:x}ULL;")
        print(f"inline constexpr size_t {name}_bit_length = {bit_length};")
        print(f"inline constexpr uint16_t {name}_raw_ticks[] = {{")
        print(format_ticks(ticks))
        print("};")
        print(
            f"inline constexpr size_t {name}_raw_len = "
            f"sizeof({name}_raw_ticks) / sizeof({name}_raw_ticks[0]);"
        )
        print("")

    print("} // namespace test_fixtures")


if __name__ == "__main__":
    main()
