// Generated by tests/fixtures/export_cpp_fixtures.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace test_fixtures
{
inline constexpr uint64_t nec_normal_00ff_34_bits = 0xcb3400ffULL;
inline constexpr size_t nec_normal_00ff_34_bit_length = 32;
inline constexpr uint16_t nec_normal_00ff_34_raw_ticks[] = {
    900, 450, 56, 169, 56, 169, 56, 169, 56, 169, 56, 169,
    56, 169, 56, 169, 56, 169, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 169, 56, 56, 56, 169, 56, 169, 56, 56,
    56, 56, 56, 169, 56, 169, 56, 56, 56, 169, 56, 56,
    56, 56, 56, 169, 56, 169, 56
};
inline constexpr size_t nec_normal_00ff_34_raw_len = sizeof(nec_normal_00ff_34_raw_ticks) / sizeof(nec_normal_00ff_34_raw_ticks[0]);

inline constexpr uint64_t nec_repeat_bits = 0xffffffffffffffffULL;
inline constexpr size_t nec_repeat_bit_length = 0;
inline constexpr uint16_t nec_repeat_raw_ticks[] = {
    900, 225, 56
};
inline constexpr size_t nec_repeat_raw_len = sizeof(nec_repeat_raw_ticks) / sizeof(nec_repeat_raw_ticks[0]);

inline constexpr uint64_t sony12_0a90_bits = 0xa90ULL;
inline constexpr size_t sony12_0a90_bit_length = 12;
inline constexpr uint16_t sony12_0a90_raw_ticks[] = {
    240, 60, 60, 60, 60, 60, 60, 60, 60, 60, 120, 60,
    60, 60, 60, 60, 120, 60, 60, 60, 120, 60, 60, 60,
    120, 60
};
inline constexpr size_t sony12_0a90_raw_len = sizeof(sony12_0a90_raw_ticks) / sizeof(sony12_0a90_raw_ticks[0]);

} // namespace test_fixtures
