// Generated by tests/fixtures/export_cpp_fixtures.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace test_fixtures
{
inline constexpr uint64_t aeha48_123456789abc_bits = 0x123456789abcULL;
inline constexpr size_t aeha48_123456789abc_bit_length = 48;
inline constexpr uint16_t aeha48_123456789abc_raw_ticks[] = {
    340, 170, 43, 43, 43, 43, 43, 128, 43, 128, 43, 128,
    43, 128, 43, 43, 43, 128, 43, 43, 43, 128, 43, 43,
    43, 128, 43, 128, 43, 43, 43, 43, 43, 128, 43, 43,
    43, 43, 43, 43, 43, 128, 43, 128, 43, 128, 43, 128,
    43, 43, 43, 43, 43, 128, 43, 128, 43, 43, 43, 128,
    43, 43, 43, 128, 43, 43, 43, 43, 43, 43, 43, 128,
    43, 43, 43, 128, 43, 128, 43, 43, 43, 43, 43, 43,
    43, 128, 43, 43, 43, 43, 43, 128, 43, 43, 43, 43,
    43, 43, 43
};
inline constexpr size_t aeha48_123456789abc_raw_len = sizeof(aeha48_123456789abc_raw_ticks) / sizeof(aeha48_123456789abc_raw_ticks[0]);

inline constexpr uint64_t jvc24_00c0de_bits = 0xc0deULL;
inline constexpr size_t jvc24_00c0de_bit_length = 24;
inline constexpr uint16_t jvc24_00c0de_raw_ticks[] = {
    844, 422, 53, 53, 53, 158, 53, 158, 53, 158, 53, 158,
    53, 53, 53, 158, 53, 158, 53, 53, 53, 53, 53, 53,
    53, 53, 53, 53, 53, 53, 53, 158, 53, 158, 53, 53,
    53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
    53, 53, 53
};
inline constexpr size_t jvc24_00c0de_raw_len = sizeof(jvc24_00c0de_raw_ticks) / sizeof(jvc24_00c0de_raw_ticks[0]);

inline constexpr uint64_t nec_normal_00ff_34_bits = 0xcb3400ffULL;
inline constexpr size_t nec_normal_00ff_34_bit_length = 32;
inline constexpr uint16_t nec_normal_00ff_34_raw_ticks[] = {
    900, 450, 56, 169, 56, 169, 56, 169, 56, 169, 56, 169,
    56, 169, 56, 169, 56, 169, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 169, 56, 56, 56, 169, 56, 169, 56, 56,
    56, 56, 56, 169, 56, 169, 56, 56, 56, 169, 56, 56,
    56, 56, 56, 169, 56, 169, 56
};
inline constexpr size_t nec_normal_00ff_34_raw_len = sizeof(nec_normal_00ff_34_raw_ticks) / sizeof(nec_normal_00ff_34_raw_ticks[0]);

inline constexpr uint64_t nec_repeat_bits = 0xffffffffffffffffULL;
inline constexpr size_t nec_repeat_bit_length = 0;
inline constexpr uint16_t nec_repeat_raw_ticks[] = {
    900, 225, 56
};
inline constexpr size_t nec_repeat_raw_len = sizeof(nec_repeat_raw_ticks) / sizeof(nec_repeat_raw_ticks[0]);

inline constexpr uint64_t panasonic48_40040100bcbd_bits = 0x40040100bcbdULL;
inline constexpr size_t panasonic48_40040100bcbd_bit_length = 48;
inline constexpr uint16_t panasonic48_40040100bcbd_raw_ticks[] = {
    350, 175, 43, 130, 43, 43, 43, 130, 43, 130, 43, 130,
    43, 130, 43, 43, 43, 130, 43, 43, 43, 43, 43, 130,
    43, 130, 43, 130, 43, 130, 43, 43, 43, 130, 43, 43,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 130, 43, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 130,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 130,
    43, 43, 43
};
inline constexpr size_t panasonic48_40040100bcbd_raw_len = sizeof(panasonic48_40040100bcbd_raw_ticks) / sizeof(panasonic48_40040100bcbd_raw_ticks[0]);

inline constexpr uint64_t rc5_300f_bits = 0x300fULL;
inline constexpr size_t rc5_300f_bit_length = 14;
inline constexpr uint16_t rc5_300f_raw_ticks[] = {
    89, 89, 89, 178, 89, 89, 89, 89, 89, 89, 89, 89,
    89, 89, 89, 89, 89, 89, 178, 89, 89, 89, 89, 89,
    89, 89
};
inline constexpr size_t rc5_300f_raw_len = sizeof(rc5_300f_raw_ticks) / sizeof(rc5_300f_raw_ticks[0]);

inline constexpr uint64_t rc5_3fff_bits = 0x3fffULL;
inline constexpr size_t rc5_3fff_bit_length = 14;
inline constexpr uint16_t rc5_3fff_raw_ticks[] = {
    89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
    89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
    89, 89, 89, 89
};
inline constexpr size_t rc5_3fff_raw_len = sizeof(rc5_3fff_raw_ticks) / sizeof(rc5_3fff_raw_ticks[0]);

inline constexpr uint64_t samsung32_e0e0_40bf_bits = 0x40bfe0e0ULL;
inline constexpr size_t samsung32_e0e0_40bf_bit_length = 32;
inline constexpr uint16_t samsung32_e0e0_40bf_raw_ticks[] = {
    450, 450, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 169, 56, 169, 56, 169, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 169, 56, 169, 56, 169, 56, 169,
    56, 169, 56, 169, 56, 169, 56, 169, 56, 169, 56, 56,
    56, 169, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 169, 56, 56, 56
};
inline constexpr size_t samsung32_e0e0_40bf_raw_len = sizeof(samsung32_e0e0_40bf_raw_ticks) / sizeof(samsung32_e0e0_40bf_raw_ticks[0]);

inline constexpr uint64_t sony12_0a90_bits = 0xa90ULL;
inline constexpr size_t sony12_0a90_bit_length = 12;
inline constexpr uint16_t sony12_0a90_raw_ticks[] = {
    240, 60, 60, 60, 60, 60, 60, 60, 60, 60, 120, 60,
    60, 60, 60, 60, 120, 60, 60, 60, 120, 60, 60, 60,
    120, 60
};
inline constexpr size_t sony12_0a90_raw_len = sizeof(sony12_0a90_raw_ticks) / sizeof(sony12_0a90_raw_ticks[0]);

} // namespace test_fixtures
